### ISSUE TITLE
Cannot read property 'gcs' of undefined after upgrade to Strapi 3.0.0

### ISSUE THREAD

**Issue by peterfortuin** [Lith/strapi-provider-upload-google-cloud-storage#43]
**Describe the bug**
When I upgrade all my dependencies of Strapi to 3.0.0 and 3.0.0-beta.20.3 of the strapi-provider-upload-google-cloud-storage I get a crash during startup:

```
yarn develop
yarn run v1.22.4
$ strapi develop
[2020-05-27T15:37:23.876Z] error TypeError: Cannot read property 'gcs' of undefined
    at mergeConfigs (/Users/user/website/cms/node_modules/strapi-provider-upload-google-cloud-storage/lib/index.js:81:63)
    at Object.init (/Users/user/website/cms/node_modules/strapi-provider-upload-google-cloud-storage/lib/index.js:91:24)
    at createProvider (/Users/user/website/cms/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:35:76)
    at module.exports (/Users/user/website/cms/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:16:36)
    at execBootstrap (/Users/user/website/cms/node_modules/strapi/lib/Strapi.js:394:15)
    at /Users/user/website/cms/node_modules/strapi/lib/Strapi.js:401:14
    at Array.map (<anonymous>)
    at Strapi.runBootstrapFunctions (/Users/user/website/cms/node_modules/strapi/lib/Strapi.js:400:55)
    at Strapi.load (/Users/user/website/cms/node_modules/strapi/lib/Strapi.js:326:16)
    at async Strapi.start (/Users/user/website/cms/node_modules/strapi/lib/Strapi.js:162:9)
[2020-05-27T15:37:23.880Z] error Bootstrap function in plugin "upload" failed
[2020-05-27T15:37:23.880Z] error Error: The provider package isn't installed. Please run `npm install strapi-provider-upload-google-cloud-storage`
    at createProvider (/Users/user/website/cms/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:40:11)
    at module.exports (/Users/user/website/cms/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:16:36)
    at execBootstrap (/Users/user/website/cms/node_modules/strapi/lib/Strapi.js:394:15)
    at /Users/user/website/cms/node_modules/strapi/lib/Strapi.js:401:14
    at Array.map (<anonymous>)
    at Strapi.runBootstrapFunctions (/Users/user/website/cms/node_modules/strapi/lib/Strapi.js:400:55)
    at Strapi.load (/Users/user/website/cms/node_modules/strapi/lib/Strapi.js:326:16)
    at async Strapi.start (/Users/user/website/cms/node_modules/strapi/lib/Strapi.js:162:9)
error Command failed with exit code 1.
```

**To Reproduce**
1. Upgrade all strapi package in package.json to 3.0.0
2. yarn install
3. yarn build --clean
4. yarn develop

**Expected behavior**
Running Strapi without crashing. 

**Screenshots**
No screenshots.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.6
 - Browser: Chrome
 - Version: 81

**Additional context**
When I replace line 80 and 81 of the index.js with the following, everything starts to work:
```
    let customGcsConfig = {};
    let customEnvGcsConfig = {};
```

I seems that reading config values has changed Strapi 3.0.0.
Additional information about migrating can be found in the [Migration guide from 3.0.0-beta.20 to 3.0.0](https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.html).

**Comment by meinvolk** [comment]
I am also getting this error after upgrading to 3.0 release.

**Comment by Lith** [comment]
Hi !

Thanks for reporting your issue. 

I will release the "stable" version of this plugin before the end of the week, for now I'm really busy and Strapi has release the latest version really quickly !

I will do my best to publish the 3.0.0 release ASAP.

Thanks !!

**Comment by peterfortuin** [comment]
Awesome @Lith ! 
Looking forward to it!

**Comment by Lith** [comment]
Thank to @dgmike to fix this problem. I will release the new version 3.0.0 now

**Comment by peterfortuin** [comment]
Thanks @dgmike and @Lith for the great work. I will try the upgrade Strapi again and will let you know the results.

**Comment by peterfortuin** [comment]
I just upgraded to Strapi 3.0.1 with the strapi-provider-upload-google-cloud-storage 3.0.0 plugin and everything is working! Thanks for the work!
