### ISSUE TITLE
[RESOLVED] Running with application default credentials in Kubernetes "Error: Required parameter: project" #1 

### ISSUE THREAD

**Issue by stfl** [Lith/strapi-provider-upload-google-cloud-storage#84]
I deploy to GKE through Gitlab. I used the minimal configuration with only providing the bucket name.
I get the following error:

```
Error uploading file to Google Cloud Storage: Required parameter: project
[2021-03-04T16:50:08.956Z] error Error: Required parameter: project
    at new ApiError (/work/pulswerk_other/agenda2030-strapi/node_modules/@google-cloud/common/build/src/util.js:59:15)
    at Util.parseHttpRespBody (/work/pulswerk_other/agenda2030-strapi/node_modules/@google-cloud/common/build/src/util.js:194:38)
    at Util.handleResp (/work/pulswerk_other/agenda2030-strapi/node_modules/@google-cloud/common/build/src/util.js:135:117)
    at /work/pulswerk_other/agenda2030-strapi/node_modules/@google-cloud/common/build/src/util.js:434:22
    at onResponse (/work/pulswerk_other/agenda2030-strapi/node_modules/retry-request/index.js:214:7)
    at /work/pulswerk_other/agenda2030-strapi/node_modules/teeny-request/build/src/index.js:219:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2021-03-04T16:50:08.956Z] error Error: Internal Server Error
    at convertToStrapiError (/work/pulswerk_other/agenda2030-strapi/node_modules/strapi-plugin-upload/errors.js:38:26)
    at Object.upload (/work/pulswerk_other/agenda2030-strapi/node_modules/strapi-plugin-upload/config/functions/bootstrap.js:35:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.uploadFileAndPersist (/work/pulswerk_other/agenda2030-strapi/node_modules/strapi-plugin-upload/services/Upload.js:154:5)
    at async Promise.all (index 0)
    at async Object.upload (/work/pulswerk_other/agenda2030-strapi/node_modules/strapi-plugin-upload/services/Upload.js:140:12)
    at async uploadFiles (/work/pulswerk_other/agenda2030-strapi/node_modules/strapi-plugin-upload/controllers/upload/admin.js:187:27)
    at async Object.upload (/work/pulswerk_other/agenda2030-strapi/node_modules/strapi-plugin-upload/controllers/Upload.js:65:5)
    at async /work/pulswerk_other/agenda2030-strapi/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
    at async /work/pulswerk_other/agenda2030-strapi/node_modules/strapi-utils/lib/policy.js:68:5
    at async /work/pulswerk_other/agenda2030-strapi/node_modules/strapi/lib/middlewares/parser/index.js:48:23
    at async /work/pulswerk_other/agenda2030-strapi/node_modules/strapi/lib/middlewares/xss/index.js:26:9
[2021-03-04T16:50:08.957Z] debug POST /upload (600 ms) 500

```

**To Reproduce**
`plugins.js`
```
module.exports = {
    upload: {
        provider: 'google-cloud-storage',
        providerOptions: {
            bucketName: '#agenda2030-uploads#',
            publicFiles: true,
            uniform: false,
            basePath: '',
        },
    },
}
```

**Comment by stfl** [comment]
The problem also shows up if I configure it with the serviceAccount so it might be related to other my configuration and is not directly related to the plugin. I will investigate further.
I would also appreciate help if you would know which config that might be.

**Comment by pabloascencao** [comment]
Hi @stfl have find the solution for this issue? I'm having the same problem and I don't find the cause.

**Comment by stfl** [comment]
No. I haven't.

**Comment by pabloascencao** [comment]
Hi @stfl I don't know if you still need it but I leave the solution i found for future devs with the same issue.

What works for me was removing the # from the bucket name and the {} from the path in the serviceAccount. That path is used for the image preview.

Also I was having an issue that in the Google config my bucket was uniform and I had to change it to match the plugin config.

Last step was that I was missing some permision to the bucket to read a write.
